apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-19T03:15:37Z"
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::204427113986:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-k1FHX0MGiC44
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::204427113986:user/ramesh
      groups:
      - trainee-binding
      username: ramesh
      
      
      
    
