apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trainee-group-role-binding
  namespace: roboshop

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trainee-group

subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: trainee-group

